require('guh').setup({})

local opts = { silent = true }
vim.keymap.set('n', '<Plug>(guh-review)', function()
  require('guh.pr').review_pr()
end, opts)
vim.keymap.set('n', '<Plug>(guh-merge)', function()
  require('guh.pr').merge_pr()
end, opts)
vim.keymap.set('n', '<Plug>(guh-merge-admin)', function()
  require('guh.pr').merge_pr(true)
end, opts)
vim.keymap.set({ 'n', 'x' }, '<Plug>(guh-comment)', '<cmd>GuhComment<cr>', opts)
vim.keymap.set('n', '<Plug>(guh-comment-overview)', '<cmd>GuhComment!<cr>', opts)
vim.keymap.set('n', '<Plug>(guh-diff)', function()
  require('guh.pr').show_pr_diff()
end, opts)
vim.keymap.set('n', '<Plug>(guh-logs)', function()
  require('guh.pr').show_ci_logs()
end, opts)
vim.keymap.set('n', '<Plug>(guh-help)', '<cmd>help guh-mappings<cr>', opts)
vim.keymap.set('n', '<Plug>(guh-refresh)', function()
  require('guh.pr').refresh()
end, opts)
