--- @alias Feat 'comment'|'commit'|'edit'|'file'|'issue'|'merge'|'pr'|'prcomments'|'prdiff'|'prlogs'|'repo'|'review'|'status'

--- Function "cmd" for `util.run_cmds`. Not added to `b:guh.jobs` (not cancellable), so must check buffer validity.
--- @alias GuhJobFn fun(buf: integer, on_stdout: fun(_: any, data: string[]), on_stderr: fun(_: any, data: string[])?, on_exit: fun())

--- Command for `util.run_cmds` command: a shell argv, or a `GuhJobFn`.
--- @alias GuhJob string[]|GuhJobFn

--- @class GuhTarget A `:Guh` target (from a cmdline arg/URL/`guh://` URI, or a programmatic feat).
--- @field owner? string
--- @field repo? string
--- @field id? integer PR/issue number.
--- @field sha? string Commit SHA.
--- @field branch? string Branch name (from "owner/repo/tree/<branch>").
--- @field is_pr? boolean nil = unknown (probe needed).
--- @field status? boolean true = the global `guh://status` page.

--- @class Notification A `b:guh.notifications` entry (keyed by slug "owner/repo#NNN").
--- @field thread_id string GitHub notification thread-id (for mark-as-read/done).
--- @field is_pr boolean Lets `pr.select` skip its PR-vs-issue probe.

--- @class BufState
--- Buffer-local b:guh dict.
--- @field chan? integer  Marks a `run_cmds` buf as "loaded". Channel-id (term=true) or a synthetic id (plain buffer).
--- @field feat? Feat Feature name
--- @field id? integer|string PR or issue number, or commit SHA.
--- @field jobs? integer[] In-flight jobs for the current `run_cmds` run.
--- @field notifications? table<string, Notification> Unread notifications on `guh://status` (keyed by slug).
--- @field pr_data? PullRequest
--- @field repo? string "owner/name"
---
--- "Info fields: denormalized values for use by 'winbar' (but possibly other consumers later).
--- @field branch string Target branch (if non-default).
--- @field n_files integer Diff file count.
--- @field n_viewed integer "Viewed" file count.
--- @field n_viewed_threads integer Unresolved threads hidden in "Viewed" files.
--- @field n_visible_threads integer Unresolved threads visible in the diff.
--- @field status string PR status label ("Open"/"Draft"/…), or CI job icon (prlogs).
--- @field status_hl string Highlight group for `status`.
--- @field title string Feat-specific title.
--- @field title_hl string Highlight group for `title`.
--- @field unread string "Unread" when the notification is unread.

--- @class Comment
--- @field body string
--- @field diff_hunk string
--- @field end_line number End of comment range (1-indexed GitHub file-line). Falls back to `originalLine` for LEFT-side / outdated threads (those have no current-HEAD `line`).
--- @field end_bufline? integer End of _rendered_ comment range (1-indexed "prdiff" buffer-line). See `start_bufline`.
--- @field id number
--- @field path string For `outdated`: a synthetic key `outdated-<thread_id>:<real_path>`.
--- @field side? 'LEFT'|'RIGHT' Diff side the comment anchors to. LEFT = deleted-line/old file, RIGHT = added/context/new file.
--- @field start_line number Start of comment range (1-indexed GitHub file-line). Falls back to `originalStartLine` for LEFT-side / outdated threads.
--- @field start_bufline? integer Start of _rendered_ comment range (1-indexed "prdiff" buffer-line). Set at render time.
--- @field updated_at string
--- @field url string
--- @field user string
--- @field outdated? boolean true if GraphQL marked the thread `isOutdated`.
--- @field in_head? boolean Thread anchors to a current-HEAD line (decides "outside" vs "outdated").
--- @field thread_id? number GraphQL thread id (root comment databaseId).
--- @field thread_node_id? string GraphQL global node id of the thread (e.g. `PRRT_kw…`). Needed by the resolveReviewThread mutation.

--- @class CommentThread
--- @field comments Comment[]
--- @field id number
--- @field end_line number End of thread range (1-indexed GitHub file-line). = head comment's `end_line`.
--- @field start_line number Start of thread range (1-indexed GitHub file-line).
--- @field url string

--- @class FileNameAndLinePair
--- @field [1] string filename
--- @field [2] number line

--- @class Issue
--- @field author table
--- @field body string
--- @field createdAt string
--- @field labels table
--- @field number number
--- @field state string
--- @field title string
--- @field updatedAt string
--- @field url string

--- @class PRCommit
--- @field oid string
--- @field messageHeadline string
--- @field messageBody string
--- @field authors table[]

--- @class CIJob A GitHub Actions check-run summary (one matrix-expanded job at the PR's head commit).
--- @field databaseId integer Workflow job id (parsed from `detailsUrl`), feeds `gh.get_pr_ci_logs`.
--- @field runId integer Workflow run id (parsed from `detailsUrl`), feeds `gh run rerun`.
--- @field name string
--- @field conclusion? string lowercase: "success", "failure", "cancelled", … (nil if in-progress).
--- @field status? string lowercase: "completed", "in_progress", "queued", …
--- @field startedAt? string
--- @field url? string Web URL of the job (`detailsUrl`).

--- @class PullRequest PR data selected from GraphQL by `gh.get_pr_data`.
--- @field node_id string GraphQL global node id (e.g. `PR_kw…`). Needed by mutations like `markFileAsViewed`.
--- @field additions number Lines added across the diff.
--- @field author table `{ login, name? }` (`name` only for User authors, not Bots).
--- @field baseRefName string
--- @field baseRefOid string
--- @field body string
--- @field changedFiles number
--- @field ci_jobs CIJob[] Latest matrix-expanded github-actions jobs at the head commit (sorted by status, name).
--- @field commits PRCommit[]
--- @field createdAt string
--- @field defaultBranch? string Repo's default branch.
--- @field deletions number Lines deleted across the diff.
--- @field headRefName string
--- @field headRefOid string
--- @field isDraft boolean
--- @field labels table
--- @field number number
--- @field reactions { content: string, reactors: { totalCount: integer } }[] Reaction groups (incl. zero-count).
--- @field reviewDecision string
--- @field reviews table
--- @field state 'OPEN'|'CLOSED'|'MERGED'
--- @field title string
--- @field url string
--- @field raw_comments Comment[] Flat per-comment list from `flatten_review_threads`.
--- @field viewed table<string, boolean> Per-file "Viewed" flag. Also for quasi-filepaths (e.g. `outdated-<id>:<path>`).
--- @field file_paths table<string, true> Set of all current paths in this PR's diff. Used to validate `markFileAsViewed` targets locally.
--- @field n_files? integer Files in the rendered diff (incl. outdated/outside virtual files). Set by `pr.load_pr`.
--- @field n_resolved integer Resolved review-thread count.
--- @field n_threads integer Total review-thread count (resolved + unresolved).
--- @field n_viewed_threads? integer Unresolved threads hidden in "Viewed" files. Set by `pr.load_pr`.
--- @field diff_stdout? string Cached raw `gh pr diff` output. Set by `pr.load_pr`.
