name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Run tests
      env:
        GH_TOKEN: ${{ github.token }}
      run: make test
